server:
  port: 8001
  servlet:
    context-path: /livedays
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/livedays?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: Bql879543~

  # 模板引擎设置
  freemarker:
    # 是否启用模板引擎
    enabled: true
    # 设定模板的加载路径
    template-loader-path: classpath:/templates/
    # Content-Type 的值
    content-type: text/html
    # 设定模板的后缀
    suffix: .ftl
    # 是否启用模板缓存
    cache: false
    # 是否优先从文件系统加载template，以支持热加载，默认为true
    prefer-file-system-access: true
  # Redis设置
  redis:
    host: 114.115.167.133
    # Redis密码
    password: Bql879543
    port: 6379
    # 数据库索引
    database: 0
    # springboot 2.0 redis默认客户客户端已换成lettuce
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认9
        max-active: 8
        # 连接池默认最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
    # 连接超时时间
    timeout: 5000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

